<?php

namespace AppBundle\Repository;

/**
 * EstadoFormularioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoFormularioRepository extends \Doctrine\ORM\EntityRepository
{
}
