<?php

namespace AppBundle\Repository;

/**
 * EstadoNotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoNotaRepository extends \Doctrine\ORM\EntityRepository
{
}
