<?php

namespace AppBundle\Repository;

/**
 * PostulanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostulanteRepository extends \Doctrine\ORM\EntityRepository
{
}
