<?php

namespace AppBundle\Repository;

/**
 * PreinscripcionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreinscripcionRepository extends \Doctrine\ORM\EntityRepository
{
}
