<?php

namespace AppBundle\Repository;

/**
 * UsuarioExternoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioExternoRepository extends \Doctrine\ORM\EntityRepository
{
}
