<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Postulante extends \AppBundle\Entity\Postulante implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'apellidos', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'nombres', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'fechaNacimiento', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'edad', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'edadal30dejunio', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'nacionalidad', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'domicilio', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'telefonos', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'viveCon', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'hnoMismaEdad', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'formularios', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'padre', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'madre'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'apellidos', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'nombres', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'fechaNacimiento', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'edad', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'edadal30dejunio', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'nacionalidad', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'domicilio', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'telefonos', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'viveCon', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'hnoMismaEdad', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'formularios', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'padre', '' . "\0" . 'AppBundle\\Entity\\Postulante' . "\0" . 'madre'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Postulante $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidos($apellidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidos', [$apellidos]);

        return parent::setApellidos($apellidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidos', []);

        return parent::getApellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombres($nombres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombres', [$nombres]);

        return parent::setNombres($nombres);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombres', []);

        return parent::getNombres();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaNacimiento($fechaNacimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaNacimiento', [$fechaNacimiento]);

        return parent::setFechaNacimiento($fechaNacimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaNacimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaNacimiento', []);

        return parent::getFechaNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdad($edad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdad', [$edad]);

        return parent::setEdad($edad);
    }

    /**
     * {@inheritDoc}
     */
    public function getEdad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdad', []);

        return parent::getEdad();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdadal30dejunio($edadal30dejunio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdadal30dejunio', [$edadal30dejunio]);

        return parent::setEdadal30dejunio($edadal30dejunio);
    }

    /**
     * {@inheritDoc}
     */
    public function getEdadal30dejunio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdadal30dejunio', []);

        return parent::getEdadal30dejunio();
    }

    /**
     * {@inheritDoc}
     */
    public function setNacionalidad($nacionalidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNacionalidad', [$nacionalidad]);

        return parent::setNacionalidad($nacionalidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getNacionalidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNacionalidad', []);

        return parent::getNacionalidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomicilio($domicilio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomicilio', [$domicilio]);

        return parent::setDomicilio($domicilio);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomicilio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomicilio', []);

        return parent::getDomicilio();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonos($telefonos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonos', [$telefonos]);

        return parent::setTelefonos($telefonos);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonos', []);

        return parent::getTelefonos();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setViveCon($viveCon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setViveCon', [$viveCon]);

        return parent::setViveCon($viveCon);
    }

    /**
     * {@inheritDoc}
     */
    public function getViveCon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getViveCon', []);

        return parent::getViveCon();
    }

    /**
     * {@inheritDoc}
     */
    public function setHnoMismaEdad($hnoMismaEdad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHnoMismaEdad', [$hnoMismaEdad]);

        return parent::setHnoMismaEdad($hnoMismaEdad);
    }

    /**
     * {@inheritDoc}
     */
    public function getHnoMismaEdad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHnoMismaEdad', []);

        return parent::getHnoMismaEdad();
    }

    /**
     * {@inheritDoc}
     */
    public function addFormulario(\AppBundle\Entity\Formulario $formulario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFormulario', [$formulario]);

        return parent::addFormulario($formulario);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFormulario(\AppBundle\Entity\Formulario $formulario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFormulario', [$formulario]);

        return parent::removeFormulario($formulario);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormularios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormularios', []);

        return parent::getFormularios();
    }

    /**
     * {@inheritDoc}
     */
    public function setPadre(\AppBundle\Entity\UsuarioExterno $padre = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPadre', [$padre]);

        return parent::setPadre($padre);
    }

    /**
     * {@inheritDoc}
     */
    public function getPadre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPadre', []);

        return parent::getPadre();
    }

    /**
     * {@inheritDoc}
     */
    public function setMadre(\AppBundle\Entity\UsuarioExterno $madre = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMadre', [$madre]);

        return parent::setMadre($madre);
    }

    /**
     * {@inheritDoc}
     */
    public function getMadre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMadre', []);

        return parent::getMadre();
    }

}
